# Generated by Django 4.1.7 on 2023-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
