# Generated by Django 4.1.7 on 2023-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
    ]
