# Generated by Django 4.1.7 on 2023-03-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
